name: bosh-bug-replication

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

releases:
- name: bosh-bug-replication
  version: latest

instance_groups:
- name: memory_hog
  azs:
  - z1
  - z2
  - z3
  instances: 3
  vm_type: minimal
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: memory_hog
    release: bosh-bug-replication

update:
  canaries: 2
  max_in_flight: 2
  canary_watch_time: 30000-60000
  update_watch_time: 5000-60000
  serial: true
