#!/bin/bash -e

RUN_DIR=/var/vcap/sys/run/memory-hog
LOG_DIR=/var/vcap/sys/log/memory-hog
PIDFILE=${RUN_DIR}/memory-hog.pid
JOB_DIR=/var/vcap/jobs/memory-hog
CERT_DIR=$JOB_DIR/config/certs

PACKAGE_DIR=/var/vcap/packages/memory-hog
ENVIRONMENT=/var/vcap/jobs/memory-hog/bin/environment.sh

case $1 in

  start)
    set +e
      killall -15 memory-hog
      killall -9 memory-hog
      killall -2 memory-hog
      killall -3 memory-hog
    set -e

    mkdir -p $RUN_DIR $LOG_DIR
    chown -R vcap:vcap $RUN_DIR $LOG_DIR

    cd $PACKAGE_DIR

    ulimit -n 8192

    source $ENVIRONMENT

    mkdir -p $STORAGE_PATH
    chown vcap:vcap $STORAGE_PATH
    chmod 755 $STORAGE_PATH

    echo $$ > $PIDFILE
    exec chpst -u vcap:vcap ./memory-hog &>> ${LOG_DIR}/memory-hog.log

    ;;

  stop)
    set +e
      killall -15 memory-hog
      killall -9 memory-hog
      killall -2 memory-hog
      killall -3 memory-hog
    set -e

    rm -f $PIDFILE

    ;;

  *)
    echo "Usage: ctl {start|stop}"

    ;;

esac
